"""
Django settings for geoartemis project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
from pathlib import Path
import os
from decouple import config
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2-)i!w)nq6+bq*8^!-q8o&pu_6752hv*^^49g5969*e$iu-v16'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = json.loads(config('DEBUG').lower())

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'geoartemis',
    'main',
    'aula_virtual',
    'accounts',
    'fullcalendar',
]
if not DEBUG:
    INSTALLED_APPS.append('storages')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not DEBUG:
    MIDDLEWARE.append('redirect_to_non_www.middleware.RedirectToNonWww')
    MIDDLEWARE.append('django.middleware.security.SecurityMiddleware')
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True


LOGIN_REDIRECT_URL = '/aula_virtual/'
ROOT_URLCONF = 'geoartemis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geoartemis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'geoartemis',
        'USER': 'postgres',
        'PASSWORD': 'sperma901',
        'HOST': 'localhost',
        'PORT': '5434',
    }
}
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''
if not DEBUG:
    import dj_database_url
    DATABASES['default'] = dj_database_url.config()

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend','accounts.backends.EmailAuthBackend']
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

STATUS = 'DOING'
# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
ZOOM_JWT_TOKEN='eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOm51bGwsImlzcyI6IklPVTdsT3VXUWgtbk44QnBMWDNwOHciLCJleHAiOjE2MjI4NjkyMDAsImlhdCI6MTU5MTQwMDM3N30.oMAGxp1dJdC1uFtgTp_OuiOzM9sG-9COgPZ74ZL0ANw'
ZOOM_USERID='profesoresgeoartemis@gmail.com'
ZOOM_PASSWORD='geoartemis1234'
LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_L10N = True

USE_TZ = True
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID') 
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY') 
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_CUSTOM_DOMAIN = '{}.s3.amazonaws.com'.format(AWS_STORAGE_BUCKET_NAME)
if DEBUG:
    STATIC_ROOT='static/'
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
else:
    CDN_ENABLED = json.loads(config('CDN_ENABLED').lower())
    AWS_DEFAULT_ACL = None
    STATIC_DISTRIBUTION_ID = config('STATIC_DISTRIBUTION_ID')
    AWS_S3_CDN_DOMAIN = '{}.cloudfront.net'.format(STATIC_DISTRIBUTION_ID)
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
    
    STORAGES = {
        "default": {
            "BACKEND": "geoartemis.storage_backends.PublicMediaStorage",
        },
        "staticfiles" : {
            "BACKEND": "geoartemis.storage_backends.StaticStorage",
        },
    }
    STATIC_LOCATION = 'static'
    
    STATIC_URL = 'https://{}/{}/'.format(AWS_S3_CUSTOM_DOMAIN, STATIC_LOCATION)
    OTHER_MEDIA_URL='https://{}/'.format(AWS_S3_CUSTOM_DOMAIN)
    AWS_PUBLIC_MEDIA_LOCATION = 'media'
    
    AWS_PRIVATE_MEDIA_LOCATION = 'media'
    PRIVATE_FILE_STORAGE = 'geoartemis.storage_backends.PrivateMediaStorage'
    
    MEDIA_URL = 'https://{}/{}/'.format(AWS_S3_CUSTOM_DOMAIN, AWS_PUBLIC_MEDIA_LOCATION)
    
    AWS_REGION="us-east-1"
COMPANY_JRA_SLUG = 'jra'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

