# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-05 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Hombre'), (1, 'Mujer')], default=0, verbose_name='sexo'),
        ),
    ]
