# Generated by Django 5.2.4 on 2025-09-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
