# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-05 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'permissions': (('view_calendars', 'Can see existing calendars'),), 'verbose_name': 'crear calendario', 'verbose_name_plural': 'Calendars'},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.CharField(blank=None, max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='shared with'),
        ),
    ]
