# Generated by Django 5.2.4 on 2025-09-15 16:38

import aula_virtual.models
import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='capacitationes/', verbose_name='file')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='company name')),
                ('short_name', models.CharField(max_length=100, unique=True, verbose_name='short name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=aula_virtual.models.upload_image_to, verbose_name='logo')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(null=True, upload_to='cursos/', verbose_name='file')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='video')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count_mounth', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='services/', verbose_name='file')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.CharField(max_length=250)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.capacitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('type_accident', models.IntegerField(choices=[(1, 'ACCIDENT'), (2, 'INCIDENT')], default=1, verbose_name='type accident')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='date')),
                ('evidence', models.FileField(null=True, upload_to='accident/', verbose_name='evidence')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(max_length=50)),
                ('time', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EspecificCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('zoom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zoom')),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(null=True, upload_to='cursosEspecificos/', verbose_name='file')),
                ('video', models.FileField(null=True, upload_to='cursosEspecificos/videos', verbose_name='video')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2025, 9, 15, 11, 38, 52, 778274), verbose_name='Fecha inicio')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duracion')),
                ('benefits', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficios')),
                ('certificate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Certificacion')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='Introduccion: ')),
                ('object', models.TextField(blank=True, null=True, verbose_name='Objectivo: ')),
                ('go_to', models.TextField(blank=True, null=True, verbose_name='Dirigido a: ')),
                ('temario', models.TextField(blank=True, null=True, verbose_name='Temario: ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.course')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='formatos/')),
                ('type_format', models.IntegerField(choices=[(1, 'VIDEOS'), (2, 'ARCHIVO')], default=2, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.especificcourse')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryFormats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='history/%Y/%m/%d')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2025, 9, 15, 11, 38, 52, 784803))),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.format')),
            ],
        ),
        migrations.CreateModel(
            name='Package_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.package')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.especificcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Package_User_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_buy', models.DateField(auto_now_add=True)),
                ('date_activated', models.DateField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='payment')),
                ('is_active', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.package')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.especificcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.company')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.CharField(max_length=250)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.service')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date_time', models.DateTimeField()),
                ('type_calendar', models.IntegerField()),
                ('charge', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('expiration', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.company')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='UseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.product')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.task')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.task')),
            ],
        ),
    ]
