# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 22:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificcourse',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Introduccion: '),
        ),
        migrations.AlterField(
            model_name='especificcourse',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 22, 28, 0, 595119), verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='historyformats',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 22, 28, 0, 605459)),
        ),
    ]
