# Generated by Django 5.2.4 on 2025-09-15 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificcourse',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 11, 57, 15, 404894), verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='historyformats',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 11, 57, 15, 411499)),
        ),
    ]
