# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0002_auto_20170529_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificcourse',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 30, 3, 28, 18, 791336), verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='historyformats',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 30, 3, 28, 18, 802702)),
        ),
        migrations.AlterField(
            model_name='package_course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='package_user_course',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.EspecificCourse'),
        ),
    ]
