# Generated by Django 5.2.4 on 2025-09-15 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0002_alter_especificcourse_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificcourse',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 12, 10, 28, 340178), verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='historyformats',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 12, 10, 28, 346813)),
        ),
    ]
