# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-03 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0005_auto_20170627_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='especificcourse',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 13, 22, 41, 401423), verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='historyformats',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 13, 22, 41, 410445)),
        ),
    ]
