# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-05 23:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0006_auto_20200603_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificcourse',
            name='zoom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zoom'),
        ),
        migrations.AlterField(
            model_name='especificcourse',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 18, 6, 9, 760400), verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='format',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='historyformats',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 18, 6, 9, 769407)),
        ),
    ]
